## Web scrapping de IMDB

Descarga la información correspondiente y guarda en un csv el top de las 250 películas mediante webscrapping. Encapsúlalo en un script.

Obtén:
* Título
* Año 
* Duración
* Posición
* Rating

In [18]:
# Si la petición te devuelve un 403, puedes probar con:
# pip install fake-useragent
# from fake_useragent import UserAgent
# ua = UserAgent()
# headers = {'User-Agent': ua.random}
# response = requests.get(url, headers=headers)

In [1]:
from bs4 import BeautifulSoup as bs
import requests
import pandas as pd

In [2]:
url = "https://www.imdb.com/chart/top/"
response = requests.get(url)
print (response)

<Response [403]>

In [6]:
from fake_useragent import UserAgent
ua = UserAgent()
headers = {'User-Agent': ua.random}
# Configuración importante para evitar bloqueos
'''
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
    'Accept-Language': 'es-ES,en;q=0.9'
}
'''
response = requests.get(url, headers=headers)
htlm = response.text
response

In [50]:
# Analizar el contenido HTML de la página
soup = bs(htlm,'html.parser')

In [8]:
# soup.h3.get_text()

In [9]:
'''
all_h3 = soup.find_all('h3')
for x in all_h3[:5]:
    print(x.get_text())
'''

"\nall_h3 = soup.find_all('h3')\nfor x in all_h3[:5]:\n    print(x.get_text())\n"

In [10]:
'''
# Selectores actualizados para 2023
movie_list = soup.select('li.ipc-metadata-list-summary-item')
    
movies = []
for movie in movie_list:
    # Extraer posición
    position = movie.select_one('h3.ipc-title__text').get_text(strip=True).split('.')[0]
        
    # Extraer título
    title = movie.select_one('h3.ipc-title__text').get_text(strip=True).split('.')[1].strip()
        
    # Extraer año y duración
    metadata = movie.select_one('div.cli-title-metadata')
    year = metadata.find_all('span')[0].text
    duration = metadata.find_all('span')[1].text if len(metadata.find_all('span')) > 1 else "N/A"
        
    # Extraer rating
    rating = movie.select_one('span.ipc-rating-star').get_text(strip=True).split()[0]
        
    movies.append({
        'Posición': position,
        'Título': title,
        'Año': year,
        'Duración': duration,
        'Rating': rating
        })

# Crear DataFrame y guardar CSV
df = pd.DataFrame(movies)
df.to_csv('top250_imdb_actualizado.csv', index=False)
print(df)
'''

'\n# Selectores actualizados para 2023\nmovie_list = soup.select(\'li.ipc-metadata-list-summary-item\')\n\nmovies = []\nfor movie in movie_list:\n    # Extraer posición\n    position = movie.select_one(\'h3.ipc-title__text\').get_text(strip=True).split(\'.\')[0]\n\n    # Extraer título\n    title = movie.select_one(\'h3.ipc-title__text\').get_text(strip=True).split(\'.\')[1].strip()\n\n    # Extraer año y duración\n    metadata = movie.select_one(\'div.cli-title-metadata\')\n    year = metadata.find_all(\'span\')[0].text\n    duration = metadata.find_all(\'span\')[1].text if len(metadata.find_all(\'span\')) > 1 else "N/A"\n\n    # Extraer rating\n    rating = movie.select_one(\'span.ipc-rating-star\').get_text(strip=True).split()[0]\n\n    movies.append({\n        \'Posición\': position,\n        \'Título\': title,\n        \'Año\': year,\n        \'Duración\': duration,\n        \'Rating\': rating\n        })\n\n# Crear DataFrame y guardar CSV\ndf = pd.DataFrame(movies)\ndf.to_csv(\'top250_imdb_actualizado.csv\', index=False)\nprint(df)\n'

In [17]:
soup.find_all('h3', class_='ipc-title__text')[1:-1]

[<h3 class="ipc-title__text">1. Cadena perpetua</h3>,
 <h3 class="ipc-title__text">2. El padrino</h3>,
 <h3 class="ipc-title__text">3. El caballero oscuro</h3>,
 <h3 class="ipc-title__text">4. El padrino parte II</h3>,
 <h3 class="ipc-title__text">5. 12 hombres sin piedad</h3>,
 <h3 class="ipc-title__text">6. El señor de los anillos: El retorno del rey</h3>,
 <h3 class="ipc-title__text">7. La lista de Schindler</h3>,
 <h3 class="ipc-title__text">8. Pulp Fiction</h3>,
 <h3 class="ipc-title__text">9. El señor de los anillos: La comunidad del anillo</h3>,
 <h3 class="ipc-title__text">10. El bueno, el feo y el malo</h3>,
 <h3 class="ipc-title__text">11. Forrest Gump</h3>,
 <h3 class="ipc-title__text">12. El señor de los anillos: Las dos torres</h3>,
 <h3 class="ipc-title__text">13. El club de la lucha</h3>,
 <h3 class="ipc-title__text">14. Origen</h3>,
 <h3 class="ipc-title__text">15. El imperio contraataca</h3>,
 <h3 class="ipc-title__text">16. Matrix</h3>,
 <h3 class="ipc-title__text">17. Uno de los nuestros</h3>,
 <h3 class="ipc-title__text">18. Interstellar</h3>,
 <h3 class="ipc-title__text">19. Alguien voló sobre el nido del cuco</h3>,
 <h3 class="ipc-title__text">20. Seven</h3>,
 <h3 class="ipc-title__text">21. Qué bello es vivir</h3>,
 <h3 class="ipc-title__text">22. El silencio de los corderos</h3>,
 <h3 class="ipc-title__text">23. Los siete samuráis</h3>,
 <h3 class="ipc-title__text">24. Salvar al soldado Ryan</h3>,
 <h3 class="ipc-title__text">25. Ciudad de Dios</h3>]

In [23]:
list_ranking = []
list_nombre = []

for x in soup.find_all('h3', class_='ipc-title__text')[1:-1]:
    list_ranking.append (x.get_text().split(". ")[0]) 
    list_nombre.append (x.get_text().split(". ")[1])# Separa en dos columnas

In [46]:
print (list_ranking)

['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '8.6']

In [ ]:
soup.find_all('div', class_ = 'sc-4b408797-7 fUdAcX cli-title-metadata')

In [36]:
list_anio = []
list_duracion = []
list_edad = []

for x in soup.find_all('span', class_ = 'sc-4b408797-8 iurwGb cli-title-metadata-item'):

    if len(x.text) == 4:
        list_anio.append (x.text)
    if len(x.text) > 4:
        list_duracion.append (x.text)
    if len(x.text) > 0 and len(x.text) <= 2:
        list_edad.append (x.text)

In [37]:
print (list_anio)
print (list_duracion)
print (list_edad)

['1994', '1972', '2008', '1974', '1957', '2003', '1993', '1994', '2001', '1966', '1994', '2002', '1999', '2010', '1980', '1999', '1990', '2014', '1975', '1995', '1946', '1991', '1954', '1998', '2002']
['2h 22m', '2h 55m', '2h 32m', '3h 22m', '1h 36m', '3h 21m', '3h 15m', '2h 34m', '2h 58m', '3h 2m', '2h 22m', '2h 59m', '2h 19m', '2h 28m', '2h 4m', '2h 16m', '2h 25m', '2h 49m', '2h 13m', '2h 7m', '2h 10m', '1h 58m', '3h 27m', '2h 49m', '2h 10m']
['13', '18', '13', '18', 'A', '13', '13', '18', '12', '14', 'A', '13', '18', '12', 'A', '18', '18', '12', '18', '18', 'A', '18', 'A', '13', '18']

In [39]:
list_rating =[]

for x in soup.find_all('span', class_= 'ipc-rating-star--rating'):
    list_rating.append (x.text)

In [40]:
print (list_rating)

['9.3', '9.2', '9.0', '9.0', '9.0', '9.0', '9.0', '8.9', '8.9', '8.8', '8.8', '8.8', '8.8', '8.8', '8.7', '8.7', '8.7', '8.7', '8.7', '8.6', '8.6', '8.6', '8.6', '8.6', '8.6']

In [43]:
df = pd.DataFrame({
    'Ranking': list_ranking,
    'Nombre': list_nombre,
    'Año': list_anio,
    'Duración': list_duracion,
    'Edad': list_edad
})

In [44]:
df

,Ranking,Nombre,Año,Duración,Edad
0,1,Cadena perpetua,1994,2h 22m,13
1,2,El padrino,1972,2h 55m,18
2,3,El caballero oscuro,2008,2h 32m,13
3,4,El padrino parte II,1974,3h 22m,18
4,5,12 hombres sin piedad,1957,1h 36m,A
5,6,El señor de los anillos: El retorno del rey,2003,3h 21m,13
6,7,La lista de Schindler,1993,3h 15m,13
7,8,Pulp Fiction,1994,2h 34m,18
8,9,El señor de los anillos: La comunidad del anillo,2001,2h 58m,12
9,10,"El bueno, el feo y el malo",1966,3h 2m,14
10,11,Forrest Gump,1994,2h 22m,A
11,12,El señor de los anillos: Las dos torres,2002,2h 59m,13
12,13,El club de la lucha,1999,2h 19m,18
13,14,Origen,2010,2h 28m,12
14,15,El imperio contraataca,1980,2h 4m,A
15,16,Matrix,1999,2h 16m,18
16,17,Uno de los nuestros,1990,2h 25m,18
17,18,Interstellar,2014,2h 49m,12
18,19,Alguien voló sobre el nido del cuco,1975,2h 13m,18
19,20,Seven,1995,2h 7m,18
20,21,Qué bello es vivir,1946,2h 10m,A
21,22,El silencio de los corderos,1991,1h 58m,18
22,23,Los siete samuráis,1954,3h 27m,A
23,24,Salvar al soldado Ryan,1998,2h 49m,13
24,25,Ciudad de Dios,2002,2h 10m,18

In [42]:
df.to_csv('top250_imdb_actualizado.csv', index=False)
print(df)

   Ranking                                            Nombre   Año Duración  \
0        1                                   Cadena perpetua  1994   2h 22m
1        2                                        El padrino  1972   2h 55m
2        3                               El caballero oscuro  2008   2h 32m
3        4                               El padrino parte II  1974   3h 22m
4        5                             12 hombres sin piedad  1957   1h 36m
5        6       El señor de los anillos: El retorno del rey  2003   3h 21m
6        7                             La lista de Schindler  1993   3h 15m
7        8                                      Pulp Fiction  1994   2h 34m
8        9  El señor de los anillos: La comunidad del anillo  2001   2h 58m
9       10                        El bueno, el feo y el malo  1966    3h 2m
10      11                                      Forrest Gump  1994   2h 22m
11      12           El señor de los anillos: Las dos torres  2002   2h 59m
12      13                               El club de la lucha  1999   2h 19m
13      14                                            Origen  2010   2h 28m
14      15                            El imperio contraataca  1980    2h 4m
15      16                                            Matrix  1999   2h 16m
16      17                               Uno de los nuestros  1990   2h 25m
17      18                                      Interstellar  2014   2h 49m
18      19               Alguien voló sobre el nido del cuco  1975   2h 13m
19      20                                             Seven  1995    2h 7m
20      21                                Qué bello es vivir  1946   2h 10m
21      22                       El silencio de los corderos  1991   1h 58m
22      23                                Los siete samuráis  1954   3h 27m
23      24                            Salvar al soldado Ryan  1998   2h 49m
24      25                                    Ciudad de Dios  2002   2h 10m

   Edad
0    13
1    18
2    13
3    18
4     A
5    13
6    13
7    18
8    12
9    14
10    A
11   13
12   18
13   12
14    A
15   18
16   18
17   12
18   18
19   18
20    A
21   18
22    A
23   13
24   18

In [ ]:
#### PARA SACAR LAS 250 PELICULAS CON JSON ####

_____________________________________________________________________________________________________

# JSON

In [51]:
import json

In [ ]:
soup.find_all ('script', {'type': 'application/ld+json'})

[<script type="application/ld+json">{"@type":"ItemList","itemListElement":[{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0111161/","name":"The Shawshank Redemption","alternateName":"Cadena perpetua","description":"A banker convicted of uxoricide forms a friendship over a quarter century with a hardened convict, while maintaining his innocence and trying to remain hopeful through simple compassion.","image":"https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":9.3,"ratingCount":3045590},"contentRating":"13","genre":"Drama","duration":"PT2H22M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0068646/","name":"The Godfather","alternateName":"El padrino","description":"The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.","image":"https://m.media-amazon.com/images/M/MV5BNTljNjllNDAtMzc0MS00ZGExLThlOTktOTRlNzc3YjA3ZWFlXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":9.2,"ratingCount":2126064},"contentRating":"18","genre":"Crime, Drama","duration":"PT2H55M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0468569/","name":"The Dark Knight","alternateName":"El caballero oscuro","description":"When a menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman, James Gordon and Harvey Dent must work together to put an end to the madness.","image":"https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":9,"ratingCount":3022443},"contentRating":"13","genre":"Action, Crime, Drama","duration":"PT2H32M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0071562/","name":"The Godfather Part II","alternateName":"El padrino parte II","description":"The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.","image":"https://m.media-amazon.com/images/M/MV5BMjQ5MzQxZTEtMmE1Yy00NjZlLTk5ODItNjI3MWIxMjk1M2U5XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":9,"ratingCount":1430228},"contentRating":"18","genre":"Crime, Drama","duration":"PT3H22M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0050083/","name":"12 Angry Men","alternateName":"12 hombres sin piedad","description":"The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.","image":"https://m.media-amazon.com/images/M/MV5BYThhOGFhODktNGEwNi00MzY2LTg3YWYtNzAzZTE0MTFlMWQxXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":9,"ratingCount":925964},"contentRating":"A","genre":"Crime, Drama","duration":"PT1H36M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0167260/","name":"The Lord of the Rings: The Return of the King","alternateName":"El señor de los anillos: El retorno del rey","description":"Gandalf and Aragorn lead the World of Men against Sauron&apos;s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.","image":"https://m.media-amazon.com/images/M/MV5BZGEzZDkzNDgtMGMzZi00NjNhLTliNWMtMTllYzQ2OTQwNGFkXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":9,"ratingCount":2078873},"contentRating":"13","genre":"Adventure, Drama, Fantasy","duration":"PT3H21M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0108052/","name":"Schindler&apos;s List","alternateName":"La lista de Schindler","description":"In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.","image":"https://m.media-amazon.com/images/M/MV5BZWUyNTJmOTMtZGM4MC00NWE2LThmZTUtZWE1NGM2YzYwZjRlXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":9,"ratingCount":1523386},"contentRating":"13","genre":"Biography, Drama, History","duration":"PT3H15M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0110912/","name":"Pulp Fiction","description":"The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.","image":"https://m.media-amazon.com/images/M/MV5BMzNlNGRkZWYtNmE0Yy00NjQyLWFmMzItYWY5NGM2YWU4OWYwXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.9,"ratingCount":2335919},"contentRating":"18","genre":"Crime, Drama","duration":"PT2H34M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0120737/","name":"The Lord of the Rings: The Fellowship of the Ring","alternateName":"El señor de los anillos: La comunidad del anillo","description":"A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.","image":"https://m.media-amazon.com/images/M/MV5BNDM0ZTRjNDAtMWFiOS00MjZiLThhZjYtNGQ0ODQ5MGE3Y2Y0XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.9,"ratingCount":2108885},"contentRating":"12","genre":"Adventure, Drama, Fantasy","duration":"PT2H58M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0060196/","name":"Il buono, il brutto, il cattivo","alternateName":"El bueno, el feo y el malo","description":"A bounty-hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.","image":"https://m.media-amazon.com/images/M/MV5BN2FmNmM5OTUtODEwMC00NDE5LWI4ZTUtZTg1ZmZlYjVjN2EyXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.8,"ratingCount":853718},"contentRating":"14","genre":"Adventure, Western","duration":"PT3H2M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0109830/","name":"Forrest Gump","description":"The history of the United States from the 1950s to the &apos;70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.","image":"https://m.media-amazon.com/images/M/MV5BOWQ0NzQ5MDItYTA3Yy00Y2ZjLWFlMGQtNjcxYzU4MWM3NzFmXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.8,"ratingCount":2380426},"contentRating":"A","genre":"Drama, Romance","duration":"PT2H22M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0167261/","name":"The Lord of the Rings: The Two Towers","alternateName":"El señor de los anillos: Las dos torres","description":"While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron&apos;s new ally, Saruman, and his hordes of Isengard.","image":"https://m.media-amazon.com/images/M/MV5BNjJhZjZlNjktZTEwYi00MmMwLTgyYTgtYmMyMmRlOWMzNmRjXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.8,"ratingCount":1874455},"contentRating":"13","genre":"Adventure, Drama, Fantasy","duration":"PT2H59M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0137523/","name":"Fight Club","alternateName":"El club de la lucha","description":"An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.","image":"https://m.media-amazon.com/images/M/MV5BOTgyOGQ1NDItNGU3Ny00MjU3LTg2YWEtNmEyYjBiMjI1Y2M5XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.8,"ratingCount":2466667},"contentRating":"18","genre":"Crime, Drama, Thriller","duration":"PT2H19M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt1375666/","name":"Inception","alternateName":"Origen","description":"A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.","image":"https://m.media-amazon.com/images/M/MV5BNTQxYmM1NzQtY2FiZS00MzRhLTljZDYtZjRmMGNiMWI3NTQxXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.8,"ratingCount":2684780},"contentRating":"12","genre":"Action, Adventure, Sci-Fi","duration":"PT2H28M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0080684/","name":"Star Wars: Episode V - The Empire Strikes Back","alternateName":"El imperio contraataca","description":"After the Empire overpowers the Rebel Alliance, Luke Skywalker begins training with Jedi Master Yoda, while Darth Vader and bounty hunter Boba Fett pursue his friends across the galaxy.","image":"https://m.media-amazon.com/images/M/MV5BZWQyNTJkMTAtZWQ0Zi00NGFlLWI2ZDktNTA4MzM5NDQ0MTk4XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.7,"ratingCount":1442625},"contentRating":"A","genre":"Action, Adventure, Fantasy","duration":"PT2H4M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0133093/","name":"The Matrix","alternateName":"Matrix","description":"When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.","image":"https://m.media-amazon.com/images/M/MV5BNGE1YzI4NzMtZTUxNi00Y2I5LTg2MmQtODE0NThmYTFmMDk0XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.7,"ratingCount":2156806},"contentRating":"18","genre":"Action, Sci-Fi","duration":"PT2H16M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0099685/","name":"GoodFellas","alternateName":"Uno de los nuestros","description":"The story of Henry Hill and his life in the mafia, covering his relationship with his wife Karen and his mob partners Jimmy Conway and Tommy DeVito.","image":"https://m.media-amazon.com/images/M/MV5BYTE0MmJhNGUtZDI5My00YThhLTk1NmItNDExOWUxMjg1YzUxXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.7,"ratingCount":1326790},"contentRating":"18","genre":"Biography, Crime, Drama","duration":"PT2H25M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0816692/","name":"Interstellar","description":"When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.","image":"https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.7,"ratingCount":2346977},"contentRating":"12","genre":"Adventure, Drama, Sci-Fi","duration":"PT2H49M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0073486/","name":"One Flew Over the Cuckoo&apos;s Nest","alternateName":"Alguien voló sobre el nido del cuco","description":"A newly admitted mental patient helps his docile companions defy the tyrannical head nurse.","image":"https://m.media-amazon.com/images/M/MV5BYjdkNjdlNDgtZTM1My00YzEwLTk5YjItYjE3YzllZTViNTVlXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.7,"ratingCount":1117157},"contentRating":"18","genre":"Drama","duration":"PT2H13M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0114369/","name":"Se7en","alternateName":"Seven","description":"Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.","image":"https://m.media-amazon.com/images/M/MV5BMjk4YWQ5YTItZTk2OS00MTcxLWIwNjctZjE3NzNhNjQzZjI2XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":1912593},"contentRating":"18","genre":"Crime, Drama, Mystery","duration":"PT2H7M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0038650/","name":"It&apos;s a Wonderful Life","alternateName":"Qué bello es vivir","description":"An angel is sent from Heaven to help a desperately frustrated businessman by showing him what life would have been like if he had never existed.","image":"https://m.media-amazon.com/images/M/MV5BOWIzZDkwM2MtMWU5Yy00NzA5LWFhMzUtMmI1Yzc4NWQzMzg2XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":527946},"contentRating":"A","genre":"Drama, Family, Fantasy","duration":"PT2H10M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0102926/","name":"The Silence of the Lambs","alternateName":"El silencio de los corderos","description":"A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.","image":"https://m.media-amazon.com/images/M/MV5BOGZiZjYxY2UtNDE5YS00NzcwLWI0NmItNjcwYThkOWMwYTdhXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":1636422},"contentRating":"18","genre":"Crime, Drama, Horror","duration":"PT1H58M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0047478/","name":"Shichinin no samurai","alternateName":"Los siete samuráis","description":"Farmers from a village exploited by bandits hire a veteran samurai for protection, and he gathers six other samurai to join him.","image":"https://m.media-amazon.com/images/M/MV5BYzc0ODMyMzctZTA5Zi00MGZhLWE0NTItZjJhOTE3OWMxZjBlXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":384270},"contentRating":"A","genre":"Action, Drama","duration":"PT3H27M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0120815/","name":"Saving Private Ryan","alternateName":"Salvar al soldado Ryan","description":"Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose comrades have been killed in action.","image":"https://m.media-amazon.com/images/M/MV5BMzU0YTgzM2EtYWNmMy00NWM1LWE0NTMtYjFhZDNlMDU1NWJmXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":1570738},"contentRating":"13","genre":"Drama, War","duration":"PT2H49M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0317248/","name":"Cidade de Deus","alternateName":"Ciudad de Dios","description":"In the slums of Rio, two kids&apos; paths diverge as one struggles to become a photographer and the other a kingpin.","image":"https://m.media-amazon.com/images/M/MV5BYjY4NGI5OTUtY2ZlZS00Zjk4LTk5N2MtN2JmYWVjNGNmMGRlXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":837826},"contentRating":"18","genre":"Crime, Drama","duration":"PT2H10M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0120689/","name":"The Green Mile","alternateName":"La milla verde","description":"A death row guard learns that a gentle giant in his charge possesses a mysterious gift.","image":"https://m.media-amazon.com/images/M/MV5BM2VlMDA2NWYtYzQxZi00NGIyLTk0OTYtMGY3ODFmOGFhMTI3XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":1486550},"contentRating":"13","genre":"Crime, Drama, Fantasy","duration":"PT3H9M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0118799/","name":"La vita è bella","alternateName":"La vida es bella","description":"When an open-minded Jewish waiter and his son become victims of the Holocaust, he uses a perfect mixture of will, humor and imagination to protect his son from the dangers around their camp.","image":"https://m.media-amazon.com/images/M/MV5BNTZhN2IwZWUtNTI2Yy00OWNjLWExZmYtOGMzN2M5NTE1MzM1XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":778723},"contentRating":"A","genre":"Comedy, Drama, Romance","duration":"PT1H56M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0103064/","name":"Terminator 2: Judgment Day","alternateName":"Terminator 2: El juicio final","description":"A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her ten year old son John from an even more advanced and powerful cyborg.","image":"https://m.media-amazon.com/images/M/MV5BNGMyMGNkMDUtMjc2Ni00NWFlLTgyODEtZTY2MzBiZTg0OWZiXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":1233265},"contentRating":"18","genre":"Action, Adventure, Sci-Fi","duration":"PT2H17M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0076759/","name":"Star Wars","alternateName":"La guerra de las galaxias","description":"Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire&apos;s world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth ...","image":"https://m.media-amazon.com/images/M/MV5BNGU3YTdiM2EtY2Y3MC00NTIzLWEzYzYtM2IxZDNhZjkwNjU1XkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":1509804},"contentRating":"A","genre":"Action, Adventure, Fantasy","duration":"PT2H1M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0088763/","name":"Back to the Future","alternateName":"Regreso al futuro","description":"Marty McFly, a 17-year-old high school student, is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his close friend, the maverick scientist Doc Brown.","image":"https://m.media-amazon.com/images/M/MV5BNzVhMDRlMzctMjgxOC00MDllLTkzZWUtZTk4ODgyNDgwZTBmXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.5,"ratingCount":1378558},"contentRating":"A","genre":"Adventure, Comedy, Sci-Fi","duration":"PT1H56M"}},{"@type":"ListItem","item":{"@type":"Movie","url":"https://www.imdb.com/title/tt0245429/","name":"Sen to Chihiro no kamikakushi","alternateName":"El viaje de Chihiro","description":"During her family&apos;s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches and spirits, and where humans are changed into beasts.","image":"https://m.media-amazon.com/images/M/MV5BMWI1OTdjN2EtOGUxYy00ZDBmLWFlNzAtNmRkZjhiMTIzOTNhXkEyXkFqcGc@._V1_.jpg","aggregateRating":{"@type":"AggregateRating","bestRating":10,"worstRating":1,"ratingValue":8.6,"ratingCount":911046},"contentRating":"A","genre":"Animation, Adventure, Family","duration":"P

In [69]:
data = json.loads (soup.find ('script', {'type': 'application/ld+json'}).text)
data

{'@type': 'ItemList',
 'itemListElement': [{'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0111161/',
    'name': 'The Shawshank Redemption',
    'alternateName': 'Cadena perpetua',
    'description': 'A banker convicted of uxoricide forms a friendship over a quarter century with a hardened convict, while maintaining his innocence and trying to remain hopeful through simple compassion.',
    'image': 'https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 9.3,
     'ratingCount': 3045590},
    'contentRating': '13',
    'genre': 'Drama',
    'duration': 'PT2H22M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0068646/',
    'name': 'The Godfather',
    'alternateName': 'El padrino',
    'description': 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
    'image': 'https://m.media-amazon.com/images/M/MV5BNTljNjllNDAtMzc0MS00ZGExLThlOTktOTRlNzc3YjA3ZWFlXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 9.2,
     'ratingCount': 2126064},
    'contentRating': '18',
    'genre': 'Crime, Drama',
    'duration': 'PT2H55M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0468569/',
    'name': 'The Dark Knight',
    'alternateName': 'El caballero oscuro',
    'description': 'When a menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman, James Gordon and Harvey Dent must work together to put an end to the madness.',
    'image': 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 9,
     'ratingCount': 3022443},
    'contentRating': '13',
    'genre': 'Action, Crime, Drama',
    'duration': 'PT2H32M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0071562/',
    'name': 'The Godfather Part II',
    'alternateName': 'El padrino parte II',
    'description': 'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.',
    'image': 'https://m.media-amazon.com/images/M/MV5BMjQ5MzQxZTEtMmE1Yy00NjZlLTk5ODItNjI3MWIxMjk1M2U5XkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 9,
     'ratingCount': 1430228},
    'contentRating': '18',
    'genre': 'Crime, Drama',
    'duration': 'PT3H22M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0050083/',
    'name': '12 Angry Men',
    'alternateName': '12 hombres sin piedad',
    'description': 'The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.',
    'image': 'https://m.media-amazon.com/images/M/MV5BYThhOGFhODktNGEwNi00MzY2LTg3YWYtNzAzZTE0MTFlMWQxXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 9,
     'ratingCount': 925964},
    'contentRating': 'A',
    'genre': 'Crime, Drama',
    'duration': 'PT1H36M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0167260/',
    'name': 'The Lord of the Rings: The Return of the King',
    'alternateName': 'El señor de los anillos: El retorno del rey',
    'description': 'Gandalf and Aragorn lead the World of Men against Sauron&apos;s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.',
    'image': 'https://m.media-amazon.com/images/M/MV5BZGEzZDkzNDgtMGMzZi00NjNhLTliNWMtMTllYzQ2OTQwNGFkXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 9,
     'ratingCount': 2078873},
    'contentRating': '13',
    'genre': 'Adventure, Drama, Fantasy',
    'duration': 'PT3H21M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0108052/',
    'name': 'Schindler&apos;s List',
    'alternateName': 'La lista de Schindler',
    'description': 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
    'image': 'https://m.media-amazon.com/images/M/MV5BZWUyNTJmOTMtZGM4MC00NWE2LThmZTUtZWE1NGM2YzYwZjRlXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 9,
     'ratingCount': 1523386},
    'contentRating': '13',
    'genre': 'Biography, Drama, History',
    'duration': 'PT3H15M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0110912/',
    'name': 'Pulp Fiction',
    'description': 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    'image': 'https://m.media-amazon.com/images/M/MV5BMzNlNGRkZWYtNmE0Yy00NjQyLWFmMzItYWY5NGM2YWU4OWYwXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.9,
     'ratingCount': 2335919},
    'contentRating': '18',
    'genre': 'Crime, Drama',
    'duration': 'PT2H34M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0120737/',
    'name': 'The Lord of the Rings: The Fellowship of the Ring',
    'alternateName': 'El señor de los anillos: La comunidad del anillo',
    'description': 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.',
    'image': 'https://m.media-amazon.com/images/M/MV5BNDM0ZTRjNDAtMWFiOS00MjZiLThhZjYtNGQ0ODQ5MGE3Y2Y0XkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.9,
     'ratingCount': 2108885},
    'contentRating': '12',
    'genre': 'Adventure, Drama, Fantasy',
    'duration': 'PT2H58M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0060196/',
    'name': 'Il buono, il brutto, il cattivo',
    'alternateName': 'El bueno, el feo y el malo',
    'description': 'A bounty-hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.',
    'image': 'https://m.media-amazon.com/images/M/MV5BN2FmNmM5OTUtODEwMC00NDE5LWI4ZTUtZTg1ZmZlYjVjN2EyXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.8,
     'ratingCount': 853718},
    'contentRating': '14',
    'genre': 'Adventure, Western',
    'duration': 'PT3H2M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0109830/',
    'name': 'Forrest Gump',
    'description': 'The history of the United States from the 1950s to the &apos;70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.',
    'image': 'https://m.media-amazon.com/images/M/MV5BOWQ0NzQ5MDItYTA3Yy00Y2ZjLWFlMGQtNjcxYzU4MWM3NzFmXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.8,
     'ratingCount': 2380426},
    'contentRating': 'A',
    'genre': 'Drama, Romance',
    'duration': 'PT2H22M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0167261/',
    'name': 'The Lord of the Rings: The Two Towers',
    'alternateName': 'El señor de los anillos: Las dos torres',
    'description': 'While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron&apos;s new ally, Saruman, and his hordes of Isengard.',
    'image': 'https://m.media-amazon.com/images/M/MV5BNjJhZjZlNjktZTEwYi00MmMwLTgyYTgtYmMyMmRlOWMzNmRjXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.8,
     'ratingCount': 1874455},
    'contentRating': '13',
    'genre': 'Adventure, Drama, Fantasy',
    'duration': 'PT2H59M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0137523/',
    'name': 'Fight Club',
    'alternateName': 'El club de la lucha',
    'description': 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.',
    'image': 'https://m.media-amazon.com/images/M/MV5BOTgyOGQ1NDItNGU3Ny00MjU3LTg2YWEtNmEyYjBiMjI1Y2M5XkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.8,
     'ratingCount': 2466667},
    'contentRating': '18',
    'genre': 'Crime, Drama, Thriller',
    'duration': 'PT2H19M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt1375666/',
    'name': 'Inception',
    'alternateName': 'Origen',
    'description': 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.',
    'image': 'https://m.media-amazon.com/images/M/MV5BNTQxYmM1NzQtY2FiZS00MzRhLTljZDYtZjRmMGNiMWI3NTQxXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.8,
     'ratingCount': 2684780},
    'contentRating': '12',
    'genre': 'Action, Adventure, Sci-Fi',
    'duration': 'PT2H28M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0080684/',
    'name': 'Star Wars: Episode V - The Empire Strikes Back',
    'alternateName': 'El imperio contraataca',
    'description': 'After the Empire overpowers the Rebel Alliance, Luke Skywalker begins training with Jedi Master Yoda, while Darth Vader and bounty hunter Boba Fett pursue his friends across the galaxy.',
    'image': 'https://m.media-amazon.com/images/M/MV5BZWQyNTJkMTAtZWQ0Zi00NGFlLWI2ZDktNTA4MzM5NDQ0MTk4XkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.7,
     'ratingCount': 1442625},
    'contentRating': 'A',
    'genre': 'Action, Adventure, Fantasy',
    'duration': 'PT2H4M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0133093/',
    'name': 'The Matrix',
    'alternateName': 'Matrix',
    'description': 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.',
    'image': 'https://m.media-amazon.com/images/M/MV5BNGE1YzI4NzMtZTUxNi00Y2I5LTg2MmQtODE0NThmYTFmMDk0XkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.7,
     'ratingCount': 2156806},
    'contentRating': '18',
    'genre': 'Action, Sci-Fi',
    'duration': 'PT2H16M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0099685/',
    'name': 'GoodFellas',
    'alternateName': 'Uno de los nuestros',
    'description': 'The story of Henry Hill and his life in the mafia, covering his relationship with his wife Karen and his mob partners Jimmy Conway and Tommy DeVito.',
    'image': 'https://m.media-amazon.com/images/M/MV5BYTE0MmJhNGUtZDI5My00YThhLTk1NmItNDExOWUxMjg1YzUxXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.7,
     'ratingCount': 1326790},
    'contentRating': '18',
    'genre': 'Biography, Crime, Drama',
    'duration': 'PT2H25M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0816692/',
    'name': 'Interstellar',
    'description': 'When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.',
    'image': 'https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.7,
     'ratingCount': 2346977},
    'contentRating': '12',
    'genre': 'Adventure, Drama, Sci-Fi',
    'duration': 'PT2H49M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0073486/',
    'name': 'One Flew Over the Cuckoo&apos;s Nest',
    'alternateName': 'Alguien voló sobre el nido del cuco',
    'description': 'A newly admitted mental patient helps his docile companions defy the tyrannical head nurse.',
    'image': 'https://m.media-amazon.com/images/M/MV5BYjdkNjdlNDgtZTM1My00YzEwLTk5YjItYjE3YzllZTViNTVlXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.7,
     'ratingCount': 1117157},
    'contentRating': '18',
    'genre': 'Drama',
    'duration': 'PT2H13M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0114369/',
    'name': 'Se7en',
    'alternateName': 'Seven',
    'description': 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.',
    'image': 'https://m.media-amazon.com/images/M/MV5BMjk4YWQ5YTItZTk2OS00MTcxLWIwNjctZjE3NzNhNjQzZjI2XkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.6,
     'ratingCount': 1912593},
    'contentRating': '18',
    'genre': 'Crime, Drama, Mystery',
    'duration': 'PT2H7M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0038650/',
    'name': 'It&apos;s a Wonderful Life',
    'alternateName': 'Qué bello es vivir',
    'description': 'An angel is sent from Heaven to help a desperately frustrated businessman by showing him what life would have been like if he had never existed.',
    'image': 'https://m.media-amazon.com/images/M/MV5BOWIzZDkwM2MtMWU5Yy00NzA5LWFhMzUtMmI1Yzc4NWQzMzg2XkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.6,
     'ratingCount': 527946},
    'contentRating': 'A',
    'genre': 'Drama, Family, Fantasy',
    'duration': 'PT2H10M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0102926/',
    'name': 'The Silence of the Lambs',
    'alternateName': 'El silencio de los corderos',
    'description': 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.',
    'image': 'https://m.media-amazon.com/images/M/MV5BOGZiZjYxY2UtNDE5YS00NzcwLWI0NmItNjcwYThkOWMwYTdhXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.6,
     'ratingCount': 1636422},
    'contentRating': '18',
    'genre': 'Crime, Drama, Horror',
    'duration': 'PT1H58M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0047478/',
    'name': 'Shichinin no samurai',
    'alternateName': 'Los siete samuráis',
    'description': 'Farmers from a village exploited by bandits hire a veteran samurai for protection, and he gathers six other samurai to join him.',
    'image': 'https://m.media-amazon.com/images/M/MV5BYzc0ODMyMzctZTA5Zi00MGZhLWE0NTItZjJhOTE3OWMxZjBlXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.6,
     'ratingCount': 384270},
    'contentRating': 'A',
    'genre': 'Action, Drama',
    'duration': 'PT3H27M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0120815/',
    'name': 'Saving Private Ryan',
    'alternateName': 'Salvar al soldado Ryan',
    'description': 'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose comrades have been killed in action.',
    'image': 'https://m.media-amazon.com/images/M/MV5BMzU0YTgzM2EtYWNmMy00NWM1LWE0NTMtYjFhZDNlMDU1NWJmXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.6,
     'ratingCount': 1570738},
    'contentRating': '13',
    'genre': 'Drama, War',
    'duration': 'PT2H49M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0317248/',
    'name': 'Cidade de Deus',
    'alternateName': 'Ciudad de Dios',
    'description': 'In the slums of Rio, two kids&apos; paths diverge as one struggles to become a photographer and the other a kingpin.',
    'image': 'https://m.media-amazon.com/images/M/MV5BYjY4NGI5OTUtY2ZlZS00Zjk4LTk5N2MtN2JmYWVjNGNmMGRlXkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.6,
     'ratingCount': 837826},
    'contentRating': '18',
    'genre': 'Crime, Drama',
    'duration': 'PT2H10M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0120689/',
    'name': 'The Green Mile',
    'alternateName': 'La milla verde',
    'description': 'A death row guard learns that a gentle giant in his charge possesses a mysterious gift.',
    'image': 'https://m.media-amazon.com/images/M/MV5BM2VlMDA2NWYtYzQxZi00NGIyLTk0OTYtMGY3ODFmOGFhMTI3XkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.6,
     'ratingCount': 1486550},
    'contentRating': '13',
    'genre': 'Crime, Drama, Fantasy',
    'duration': 'PT3H9M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0118799/',
    'name': 'La vita è bella',
    'alternateName': 'La vida es bella',
    'description': 'When an open-minded Jewish waiter and his son become victims of the Holocaust, he uses a perfect mixture of will, humor and imagination to protect his son from the dangers around their camp.',
    'image': 'https://m.media-amazon.com/images/M/MV5BNTZhN2IwZWUtNTI2Yy00OWNjLWExZmYtOGMzN2M5NTE1MzM1XkEyXkFqcGc@._V1_.jpg',
    'aggregateRating': {'@type': 'AggregateRating',
     'bestRating': 10,
     'worstRating': 1,
     'ratingValue': 8.6,
     'ratingCount': 778723},
    'contentRating': 'A',
    'genre': 'Comedy, Drama, Romance',
    'duration': 'PT1H56M'}},
  {'@type': 'ListItem',
   'item': {'@type': 'Movie',
    'url': 'https://www.imdb.com/title/tt0103064/',
    'name': 'Terminator 2: Judgment Day',
    'alternateName': 'Terminator 2: El juicio final',

In [83]:
data_2= json.loads (soup.find ('script', {'id': '__NEXT_DATA__'}).text)

In [62]:
dict_pelicula = {
    'Ranking': [],
    'Nombre': [],
    'Año': [],
    'Duración': [],
    'Edad': []
}
data

{'props': {'pageProps': {'initialRefinerQueryInfo': {'queryContext': {'personalized': False,
     'serverSideCacheable': True},
    'queryVariables': {}},
   'pageData': {'chartTitles': {'edges': [{'currentRank': 1,
       'node': {'id': 'tt0111161',
        'titleText': {'text': 'Cadena perpetua', '__typename': 'TitleText'},
        'titleType': {'id': 'movie',
         'text': 'Movie',
         'canHaveEpisodes': False,
         'displayableProperty': {'value': {'plainText': '',
           '__typename': 'Markdown'},
          '__typename': 'DisplayableTitleTypeProperty'},
         '__typename': 'TitleType'},
        'originalTitleText': {'text': 'The Shawshank Redemption',
         '__typename': 'TitleText'},
        'primaryImage': {'id': 'rm1690056449',
         'width': 1200,
         'height': 1800,
         'url': 'https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_.jpg',
         'caption': {'plainText': 'Tim Robbins in Cadena perpetua (1994)',
          '__typename': 'Markdown'},
         '__typename': 'Image'},
        'releaseYear': {'year': 1994,
         'endYear': None,
         '__typename': 'YearRange'},
        'ratingsSummary': {'aggregateRating': 9.3,
         'voteCount': 3045590,
         '__typename': 'RatingsSummary'},
        'runtime': {'seconds': 8520, '__typename': 'Runtime'},
        'certificate': {'rating': '13', '__typename': 'Certificate'},
        'canRate': {'isRatable': True, '__typename': 'CanRate'},
        'titleGenres': {'genres': [{'genre': {'text': 'Drama',
            '__typename': 'GenreItem'},
           '__typename': 'TitleGenre'}],
         '__typename': 'TitleGenres'},
        'canHaveEpisodes': False,
        'series': None,
        'latestTrailer': {'id': 'vi3877612057', '__typename': 'Video'},
        'plot': {'plotText': {'plainText': 'A banker convicted of uxoricide forms a friendship over a quarter century with a hardened convict, while maintaining his innocence and trying to remain hopeful through simple compassion.',
          '__typename': 'Markdown'},
         '__typename': 'Plot'},
        'releaseDate': {'day': 24,
         'month': 2,
         'year': 1995,
         '__typename': 'ReleaseDate'},
        'productionStatus': {'currentProductionStage': {'id': 'released',
          'text': 'Released',
          '__typename': 'ProductionStage'},
         '__typename': 'ProductionStatusDetails'},
        '__typename': 'Title'},
       '__typename': 'ChartTitleEdge'},
      {'currentRank': 2,
       'node': {'id': 'tt0068646',
        'titleText': {'text': 'El padrino', '__typename': 'TitleText'},
        'titleType': {'id': 'movie',
         'text': 'Movie',
         'canHaveEpisodes': False,
         'displayableProperty': {'value': {'plainText': '',
           '__typename': 'Markdown'},
          '__typename': 'DisplayableTitleTypeProperty'},
         '__typename': 'TitleType'},
        'originalTitleText': {'text': 'The Godfather',
         '__typename': 'TitleText'},
        'primaryImage': {'id': 'rm3349315586',
         'width': 456,
         'height': 643,
         'url': 'https://m.media-amazon.com/images/M/MV5BNTljNjllNDAtMzc0MS00ZGExLThlOTktOTRlNzc3YjA3ZWFlXkEyXkFqcGc@._V1_.jpg',
         'caption': {'plainText': 'El padrino (1972)',
          '__typename': 'Markdown'},
         '__typename': 'Image'},
        'releaseYear': {'year': 1972,
         'endYear': None,
         '__typename': 'YearRange'},
        'ratingsSummary': {'aggregateRating': 9.2,
         'voteCount': 2126064,
         '__typename': 'RatingsSummary'},
        'runtime': {'seconds': 10500, '__typename': 'Runtime'},
        'certificate': {'rating': '18', '__typename': 'Certificate'},
        'canRate': {'isRatable': True, '__typename': 'CanRate'},
        'titleGenres': {'genres': [{'genre': {'text': 'Crime',
            '__typename': 'GenreItem'},
           '__typename': 'TitleGenre'},
          {'genre': {'text': 'Drama', '__typename': 'GenreItem'},
           '__typename': 'TitleGenre'}],
         '__typename': 'TitleGenres'},
        'canHaveEpisodes': False,
        'series': None,
        'latestTrailer': {'id': 'vi1629995801', '__typename': 'Video'},
        'plot': {'plotText': {'plainText': 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
          '__typename': 'Markdown'},
         '__typename': 'Plot'},
        'releaseDate': {'day': 20,
         'month': 10,
         'year': 1972,
         '__typename': 'ReleaseDate'},
        'productionStatus': {'currentProductionStage': {'id': 'released',
          'text': 'Released',
          '__typename': 'ProductionStage'},
         '__typename': 'ProductionStatusDetails'},
        '__typename': 'Title'},
       '__typename': 'ChartTitleEdge'},
      {'currentRank': 3,
       'node': {'id': 'tt0468569',
        'titleText': {'text': 'El caballero oscuro',
         '__typename': 'TitleText'},
        'titleType': {'id': 'movie',
         'text': 'Movie',
         'canHaveEpisodes': False,
         'displayableProperty': {'value': {'plainText': '',
           '__typename': 'Markdown'},
          '__typename': 'DisplayableTitleTypeProperty'},
         '__typename': 'TitleType'},
        'originalTitleText': {'text': 'The Dark Knight',
         '__typename': 'TitleText'},
        'primaryImage': {'id': 'rm4023877632',
         'width': 1383,
         'height': 2048,
         'url': 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg',
         'caption': {'plainText': 'Christian Bale in El caballero oscuro (2008)',
          '__typename': 'Markdown'},
         '__typename': 'Image'},
        'releaseYear': {'year': 2008,
         'endYear': None,
         '__typename': 'YearRange'},
        'ratingsSummary': {'aggregateRating': 9,
         'voteCount': 3022443,
         '__typename': 'RatingsSummary'},
        'runtime': {'seconds': 9120, '__typename': 'Runtime'},
        'certificate': {'rating': '13', '__typename': 'Certificate'},
        'canRate': {'isRatable': True, '__typename': 'CanRate'},
        'titleGenres': {'genres': [{'genre': {'text': 'Action',
            '__typename': 'GenreItem'},
           '__typename': 'TitleGenre'},
          {'genre': {'text': 'Crime', '__typename': 'GenreItem'},
           '__typename': 'TitleGenre'},
          {'genre': {'text': 'Drama', '__typename': 'GenreItem'},
           '__typename': 'TitleGenre'}],
         '__typename': 'TitleGenres'},
        'canHaveEpisodes': False,
        'series': None,
        'latestTrailer': {'id': 'vi324468761', '__typename': 'Video'},
        'plot': {'plotText': {'plainText': 'When a menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman, James Gordon and Harvey Dent must work together to put an end to the madness.',
          '__typename': 'Markdown'},
         '__typename': 'Plot'},
        'releaseDate': {'day': 13,
         'month': 8,
         'year': 2008,
         '__typename': 'ReleaseDate'},
        'productionStatus': {'currentProductionStage': {'id': 'released',
          'text': 'Released',
          '__typename': 'ProductionStage'},
         '__typename': 'ProductionStatusDetails'},
        '__typename': 'Title'},
       '__typename': 'ChartTitleEdge'},
      {'currentRank': 4,
       'node': {'id': 'tt0071562',
        'titleText': {'text': 'El padrino parte II',
         '__typename': 'TitleText'},
        'titleType': {'id': 'movie',
         'text': 'Movie',
         'canHaveEpisodes': False,
         'displayableProperty': {'value': {'plainText': '',
           '__typename': 'Markdown'},
          '__typename': 'DisplayableTitleTypeProperty'},
         '__typename': 'TitleType'},
        'originalTitleText': {'text': 'The Godfather Part II',
         '__typename': 'TitleText'},
        'primaryImage': {'id': 'rm2697235201',
         'width': 1529,
         'height': 1975,
         'url': 'https://m.media-amazon.com/images/M/MV5BMjQ5MzQxZTEtMmE1Yy00NjZlLTk5ODItNjI3MWIxMjk1M2U5XkEyXkFqcGc@._V1_.jpg',
         'caption': {'plainText': 'Al Pacino in El padrino parte II (1974)',
          '__typename': 'Markdown'},
         '__typename': 'Image'},
        'releaseYear': {'year': 1974,
         'endYear': None,
         '__typename': 'YearRange'},
        'ratingsSummary': {'aggregateRating': 9,
         'voteCount': 1430228,
         '__typename': 'RatingsSummary'},
        'runtime': {'seconds': 12120, '__typename': 'Runtime'},
        'certificate': {'rating': '18', '__typename': 'Certificate'},
        'canRate': {'isRatable': True, '__typename': 'CanRate'},
        'titleGenres': {'genres': [{'genre': {'text': 'Crime',
            '__typename': 'GenreItem'},
           '__typename': 'TitleGenre'},
          {'genre': {'text': 'Drama', '__typename': 'GenreItem'},
           '__typename': 'TitleGenre'}],
         '__typename': 'TitleGenres'},
        'canHaveEpisodes': False,
        'series': None,
        'latestTrailer': {'id': 'vi696162841', '__typename': 'Video'},
        'plot': {'plotText': {'plainText': 'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.',
          '__typename': 'Markdown'},
         '__typename': 'Plot'},
        'releaseDate': {'day': 13,
         'month': 10,
         'year': 1975,
         '__typename': 'ReleaseDate'},
        'productionStatus': {'currentProductionStage': {'id': 'released',
          'text': 'Released',
          '__typename': 'ProductionStage'},
         '__typename': 'ProductionStatusDetails'},
        '__typename': 'Title'},
       '__typename': 'ChartTitleEdge'},
      {'currentRank': 5,
       'node': {'id': 'tt0050083',
        'titleText': {'text': '12 hombres sin piedad',
         '__typename': 'TitleText'},
        'titleType': {'id': 'movie',
         'text': 'Movie',
         'canHaveEpisodes': False,
         'displayableProperty': {'value': {'plainText': '',
           '__typename': 'Markdown'},
          '__typename': 'DisplayableTitleTypeProperty'},
         '__typename': 'TitleType'},
        'originalTitleText': {'text': '12 Angry Men',
         '__typename': 'TitleText'},
        'primaryImage': {'id': 'rm1391032064',
         'width': 678,
         'height': 982,
         'url': 'https://m.media-amazon.com/images/M/MV5BYThhOGFhODktNGEwNi00MzY2LTg3YWYtNzAzZTE0MTFlMWQxXkEyXkFqcGc@._V1_.jpg',
         'caption': {'plainText': '12 hombres sin piedad (1957)',
          '__typename': 'Markdown'},
         '__typename': 'Image'},
        'releaseYear': {'year': 1957,
         'endYear': None,
         '__typename': 'YearRange'},
        'ratingsSummary': {'aggregateRating': 9,
         'voteCount': 925964,
         '__typename': 'RatingsSummary'},
        'runtime': {'seconds': 5760, '__typename': 'Runtime'},
        'certificate': {'rating': 'A', '__typename': 'Certificate'},
        'canRate': {'isRatable': True, '__typename': 'CanRate'},
        'titleGenres': {'genres': [{'genre': {'text': 'Crime',
            '__typename': 'GenreItem'},
           '__typename': 'TitleGenre'},
          {'genre': {'text': 'Drama', '__typename': 'GenreItem'},
           '__typename': 'TitleGenre'}],
         '__typename': 'TitleGenres'},
        'canHaveEpisodes': False,
        'series': None,
        'latestTrailer': {'id': 'vi2924462873', '__typename': 'Video'},
        'plot': {'plotText': {'plainText': 'The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.',
          '__typename': 'Markdown'},
         '__typename': 'Plot'},
        'releaseDate': {'day': 10,
         'month': 4,
         'year': 1957,
         '__typename': 'ReleaseDate'},
        'productionStatus': {'currentProductionStage': {'id': 'released',
          'text': 'Released',
          '__typename': 'ProductionStage'},
         '__typename': 'ProductionStatusDetails'},
        '__typename': 'Title'},
       '__typename': 'ChartTitleEdge'},
      {'currentRank': 6,
       'node': {'id': 'tt0167260',
        'titleText': {'text': 'El señor de los anillos: El retorno del rey',
         '__typename': 'TitleText'},
        'titleType': {'id': 'movie',
         'text': 'Movie',
         'canHaveEpisodes': False,
         'displayableProperty': {'value': {'plainText': '',
           '__typename': 'Markdown'},
          '__typename': 'DisplayableTitleTypeProperty'},
         '__typename': 'TitleType'},
        'originalTitleText': {'text': 'The Lord of the Rings: The Return of the King',
         '__typename': 'TitleText'},
        'primaryImage': {'id': 'rm622753536',
         'width': 215,
         'height': 290,
         'url': 'https://m.media-amazon.com/images/M/MV5BZGEzZDkzNDgtMGMzZi00NjNhLTliNWMtMTllYzQ2OTQwNGFkXkEyXkFqcGc@._V1_.jpg',
         'caption': {'plainText': 'Liv Tyler, Sean Astin, Elijah Wood, Viggo Mortensen, Ian McKellen, and Andy Serkis in El señor de los anillos: El retorno del rey (2003)',
          '__typename': 'Markdown'},
         '__typename': 'Image'},
        'releaseYear': {'year': 2003,
         'endYear': None,
         '__typename': 'YearRange'},
        'ratingsSummary': {'aggregateRating': 9,
         'voteCount': 2078873,
         '__typename': 'RatingsSummary'},
        'runtime': {'seconds': 12060, '__typename': 'Runtime'},
        'certificate': {'rating': '13', '__typename': 'Certificate'},
        'canRate': {'isRatable': True, '__typename': 'CanRate'},
        'titleGenres': {'genres': [{'genre': {'text': 'Adventure',
            '__typename': 'GenreItem'},
           '__typename': 'TitleGenre'},
          {'genre': {'text': 'Drama', '__typename': 'GenreItem'},
           '__typename': 'TitleGenre'},
          {'genre': {'text': 'Fantasy', '__typename': 'GenreItem'},
           '__typename': 'TitleGenre'}],
         '__typename': 'TitleGenres'},
        'canHaveEpisodes': False,
        'series': None,
        'latestTrailer': {'id': 'vi2081145881', '__typename': 'Video'},
        'plot': {'plotText': {'plainText': "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
          '__typename': 'Markdown'},
         '__typename': 'Plot'},
        'releaseDate': {'day': 17,
         'month': 12,
         'year': 2003,
         '__typename': 'ReleaseDate'},
        'productionStatus': {'currentProductionStage': {'id': 'released',
          'text': 'Released',
          '__typename': 'ProductionStage'},
         '__typename': 'ProductionStatusDetails'},
        '__typename': 'Title'},
       '__typename': 'ChartTitleEdge'},
      {'currentRank': 7,
       'node': {'id': 'tt0108052',
        'titleText': {'text': 'La lista de Schindler',
         '__typename': 'TitleText'},
        'titleType': {'id': 'movie',
         'text': 'Movie',
         'canHaveEpisodes': False,
         'displayableProperty': {'value': {'plainText': '',
           '__typename': 'Markdown'},
          '__typename': 'DisplayableTitleTypeProperty'},
         '__typename': 'TitleType'},
        'originalTitleText': {'text': "Schindler's List",
         '__typename': 'TitleText'},
        'primaryImage': {'id': 'rm1609135872',
         'width': 600,
         'height': 850,
         'url': 'https://m.media-amazon.com/images/M/MV5BZWUyNTJmOTMtZGM4MC00NWE2LThmZTUtZWE1NGM2YzYwZjRlXkEyXkFqcGc@._V1_.jpg',
         'caption': {'plainText': 'La lista de Schindler (1993)',
          '__typename': 'Markdown'},
         '__typename': 'Image'},
        'releaseYear': {'year': 1993,
         'endYear': None,
         '__typename': 'YearRange'},
        'ratingsSummary': {'aggregateRating': 9,
         'voteCount': 1523386,
         '__typename': 'RatingsSummary'},
        'runtime': {'seconds': 11700, '__typename': 'Runtime'},
        'certificate': {'rating': '13', '__typename': 'Certificate'},
        'canRate': {'isRatable': True, '__typename': 'CanRate'},
        'titleGenres': {'genres': [{'genre': {'text': 'Biography',
            '__typename': 'GenreItem'},
           '__typename': 'TitleGenre'},
          {'genre': {'text': 'Drama', '__typename': 'GenreItem'},
           '__typename': 'TitleGenre'},
          {'genre': {'text': 'History', '__typename': 'GenreItem'},
           '__typename': 'TitleGenre'}],
         '__typename': 'TitleGenres'},
        'canHaveEpisodes': False,
        'series': None,
        'latestTrailer': {'id': 'vi1158527769', '__typename': 'Video'},
        'plot': {'plotText': {'plainText': 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
          '__typename': 'Markdown'},
         '__typename': 'Plot'},
        'releaseDate': {'day': 4,
         'month': 3,
         'year': 1994,
         '__typename': 'ReleaseDate'},
        'productionStatus': {'currentProductionStage': {'id': 'released',
          'text': 'Released',
          '__typename': 'ProductionStage'},
         '__typename': 'ProductionStatusDetails'},
        '__typename': 'Title'},
       '__typename': 'ChartTitleEdge'},
      {'currentRank': 8,
       'node': {'id': 'tt0110912',
        'titleText': {'text': 'Pulp Fiction', '__typename': 'TitleText'},
        'titleType': {'id': 'movie',
         'text': 'Movie',
         'canHaveEpisodes': False,
         'displayableProperty': {'value': {'plainText': '',
           '__typename': 'Markdown'},
          '__typename': 'DisplayableTitleTypeProperty'},
         '__typename': 'TitleType'},
        'originalTitleText': {'text': 'Pulp Fiction',
         '__typename': 'TitleText'},
        'primaryImage': {'id': 'rm4283528192',
         'width': 1716,
         'height': 2362,
         'url': 'https://m.media-amazon.com/images/M/MV5BMzNlNGRkZWYtNmE0Yy00NjQyLWFmMzItYWY5NGM2YWU4OWYwXkEyXkFqcGc@._V1_.jpg',
         'caption': {'plainText': 'Uma Thurman in Pulp Fiction (1994)',
          '__typename': 'Markdown'},
         '__typename': 'Image'},
        'releaseYear': {'year': 1994,
         'endYear': None,
         '__typename': 'YearRange'},
        'ratingsSummary': {'aggregateRating': 8.9,
         'voteCount': 2335919,
         '__typename': 'RatingsSummary'},
        'runtime': {'seconds': 9240, '__typename': 'Runtime'},
        'certificate': {'rating': '18', '__typename': 'Certificate'},
        'canRate': {'isRatable': True, '__typename': 'CanRate'},
        'titleGenres': {'genres': [{'genre': {'text': 'Crime',
            '__typename': 'GenreItem'},
           '__typename': 'TitleGenre'},
          {'genre': {'text': 'Drama', '__typename': 'GenreItem'},
           '__typename': 'TitleGenre'}],
         '__typename': 'TitleGenres'},
        'canHaveEpisodes': False,
        'series': None,
        'latestTrailer': {'id': 'vi2620371481', '__typename': 'Video'},
        'plot': {'plotText': {'plainText': 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
          '__typename': 'Markdown'},
         '__typename': 'Plot'},
        'releaseDate': {'day': 13,
         'month': 1,
         'year': 1995,
         '__typename': 'ReleaseDate'},
        'productionStatus': {'currentProductionStage': {'id': 'released',
          'text': 'Released',
          '__typename': 'ProductionStage'},
         '__typename': 'ProductionStatusDetails'},
        '__typename': 'Title'},
       '__typename': 'ChartTitleEdge'},
      {'currentRank': 9,
       'node': {'id': 'tt0120737',
        'titleText': {'text': 'El señor de los anillos: La comunidad del anillo',
         '__typename': 'TitleText'},
        'titleType': {'id': 'movie',

In [59]:
data['itemListElement'][0]['item']['alternateName']

'Cadena perpetua'

In [60]:
data['itemListElement'][0]['item']['duration']

'PT2H22M'

In [ ]:
i = 1
for x in data['itemListElement']:
    print('Ranking:', i)
    print('Titulo:', x['item'].get('alternateName') or x['item'].get ('name'))
    print('Rating:', x['item']['aggregateRating']['ratingValue'])
    print('Duracion:', x['item']['duration'][2:])
    i = i +1

Ranking: 1
Titulo: Cadena perpetua
Rating: 9.3
Duracion: 2H22M
Ranking: 2
Titulo: El padrino
Rating: 9.2
Duracion: 2H55M
Ranking: 3
Titulo: El caballero oscuro
Rating: 9
Duracion: 2H32M
Ranking: 4
Titulo: El padrino parte II
Rating: 9
Duracion: 3H22M
Ranking: 5
Titulo: 12 hombres sin piedad
Rating: 9
Duracion: 1H36M
Ranking: 6
Titulo: El señor de los anillos: El retorno del rey
Rating: 9
Duracion: 3H21M
Ranking: 7
Titulo: La lista de Schindler
Rating: 9
Duracion: 3H15M
Ranking: 8
Titulo: Pulp Fiction
Rating: 8.9
Duracion: 2H34M
Ranking: 9
Titulo: El señor de los anillos: La comunidad del anillo
Rating: 8.9
Duracion: 2H58M
Ranking: 10
Titulo: El bueno, el feo y el malo
Rating: 8.8
Duracion: 3H2M
Ranking: 11
Titulo: Forrest Gump
Rating: 8.8
Duracion: 2H22M
Ranking: 12
Titulo: El señor de los anillos: Las dos torres
Rating: 8.8
Duracion: 2H59M
Ranking: 13
Titulo: El club de la lucha
Rating: 8.8
Duracion: 2H19M
Ranking: 14
Titulo: Origen
Rating: 8.8
Duracion: 2H28M
Ranking: 15
Titulo: El imperio contraataca
Rating: 8.7
Duracion: 2H4M
Ranking: 16
Titulo: Matrix
Rating: 8.7
Duracion: 2H16M
Ranking: 17
Titulo: Uno de los nuestros
Rating: 8.7
Duracion: 2H25M
Ranking: 18
Titulo: Interstellar
Rating: 8.7
Duracion: 2H49M
Ranking: 19
Titulo: Alguien voló sobre el nido del cuco
Rating: 8.7
Duracion: 2H13M
Ranking: 20
Titulo: Seven
Rating: 8.6
Duracion: 2H7M
Ranking: 21
Titulo: Qué bello es vivir
Rating: 8.6
Duracion: 2H10M
Ranking: 22
Titulo: El silencio de los corderos
Rating: 8.6
Duracion: 1H58M
Ranking: 23
Titulo: Los siete samuráis
Rating: 8.6
Duracion: 3H27M
Ranking: 24
Titulo: Salvar al soldado Ryan
Rating: 8.6
Duracion: 2H49M
Ranking: 25
Titulo: Ciudad de Dios
Rating: 8.6
Duracion: 2H10M
Ranking: 26
Titulo: La milla verde
Rating: 8.6
Duracion: 3H9M
Ranking: 27
Titulo: La vida es bella
Rating: 8.6
Duracion: 1H56M
Ranking: 28
Titulo: Terminator 2: El juicio final
Rating: 8.6
Duracion: 2H17M
Ranking: 29
Titulo: La guerra de las galaxias
Rating: 8.6
Duracion: 2H1M
Ranking: 30
Titulo: Regreso al futuro
Rating: 8.5
Duracion: 1H56M
Ranking: 31
Titulo: El viaje de Chihiro
Rating: 8.6
Duracion: 2H4M
Ranking: 32
Titulo: El pianista
Rating: 8.5
Duracion: 2H30M
Ranking: 33
Titulo: Gladiator (El gladiador)
Rating: 8.5
Duracion: 2H35M
Ranking: 34
Titulo: Parásitos
Rating: 8.5
Duracion: 2H12M
Ranking: 35
Titulo: Psicosis
Rating: 8.5
Duracion: 1H49M
Ranking: 36
Titulo: El rey león
Rating: 8.5
Duracion: 1H28M
Ranking: 37
Titulo: La tumba de las luciérnagas
Rating: 8.5
Duracion: 1H28M
Ranking: 38
Titulo: Infiltrados
Rating: 8.5
Duracion: 2H31M
Ranking: 39
Titulo: Whiplash
Rating: 8.5
Duracion: 1H46M
Ranking: 40
Titulo: Harakiri
Rating: 8.6
Duracion: 2H13M
Ranking: 41
Titulo: El truco final (El prestigio)
Rating: 8.5
Duracion: 2H10M
Ranking: 42
Titulo: American History X
Rating: 8.5
Duracion: 1H59M
Ranking: 43
Titulo: El profesional (Léon)
Rating: 8.5
Duracion: 1H50M
Ranking: 44
Titulo: Spider-Man: Cruzando el multiverso
Rating: 8.5
Duracion: 2H20M
Ranking: 45
Titulo: Casablanca
Rating: 8.5
Duracion: 1H42M
Ranking: 46
Titulo: Sospechosos habituales
Rating: 8.5
Duracion: 1H46M
Ranking: 47
Titulo: Intocable
Rating: 8.5
Duracion: 1H52M
Ranking: 48
Titulo: Cinema Paradiso
Rating: 8.5
Duracion: 2H54M
Ranking: 49
Titulo: Alien, el octavo pasajero
Rating: 8.5
Duracion: 1H57M
Ranking: 50
Titulo: Tiempos modernos
Rating: 8.5
Duracion: 1H27M
Ranking: 51
Titulo: La ventana indiscreta
Rating: 8.5
Duracion: 1H52M
Ranking: 52
Titulo: Hasta que llegó su hora
Rating: 8.5
Duracion: 2H46M
Ranking: 53
Titulo: Django desencadenado
Rating: 8.5
Duracion: 2H45M
Ranking: 54
Titulo: Luces de la ciudad
Rating: 8.5
Duracion: 1H27M
Ranking: 55
Titulo: Apocalypse Now
Rating: 8.4
Duracion: 2H27M
Ranking: 56
Titulo: Dune: Parte dos
Rating: 8.5
Duracion: 2H46M
Ranking: 57
Titulo: WALL·E
Rating: 8.4
Duracion: 1H38M
Ranking: 58
Titulo: Memento
Rating: 8.4
Duracion: 1H53M
Ranking: 59
Titulo: En busca del arca perdida
Rating: 8.4
Duracion: 1H55M
Ranking: 60
Titulo: La vida de los otros
Rating: 8.4
Duracion: 2H17M
Ranking: 61
Titulo: Vengadores: Infinity War
Rating: 8.4
Duracion: 2H29M
Ranking: 62
Titulo: El crepúsculo de los dioses
Rating: 8.4
Duracion: 1H50M
Ranking: 63
Titulo: Spider-Man: Un nuevo universo
Rating: 8.4
Duracion: 1H57M
Ranking: 64
Titulo: Testigo de cargo
Rating: 8.4
Duracion: 1H56M
Ranking: 65
Titulo: Senderos de gloria
Rating: 8.4
Duracion: 1H28M
Ranking: 66
Titulo: El resplandor
Rating: 8.4
Duracion: 2H26M
Ranking: 67
Titulo: El gran dictador
Rating: 8.4
Duracion: 2H5M
Ranking: 68
Titulo: 12th Fail
Rating: 8.7
Duracion: 2H27M
Ranking: 69
Titulo: Malditos bastardos
Rating: 8.4
Duracion: 2H33M
Ranking: 70
Titulo: Aliens: El regreso
Rating: 8.4
Duracion: 2H17M
Ranking: 71
Titulo: El caballero oscuro: La leyenda renace
Rating: 8.4
Duracion: 2H44M
Ranking: 72
Titulo: Coco
Rating: 8.4
Duracion: 1H45M
Ranking: 73
Titulo: Amadeus
Rating: 8.4
Duracion: 2H40M
Ranking: 74
Titulo: Toy Story
Rating: 8.3
Duracion: 1H21M
Ranking: 75
Titulo: Vengadores: Endgame
Rating: 8.4
Duracion: 3H1M
Ranking: 76
Titulo: El indomable Will Hunting
Rating: 8.3
Duracion: 2H6M
Ranking: 77
Titulo: Old Boy
Rating: 8.3
Duracion: 2H
Ranking: 78
Titulo: ¿Teléfono rojo? Volamos hacia Moscú
Rating: 8.3
Duracion: 1H35M
Ranking: 79
Titulo: El submarino (Das Boot)
Rating: 8.4
Duracion: 2H29M
Ranking: 80
Titulo: Braveheart
Rating: 8.3
Duracion: 2H58M
Ranking: 81
Titulo: American Beauty
Rating: 8.3
Duracion: 2H2M
Ranking: 82
Titulo: La princesa Mononoke
Rating: 8.3
Duracion: 2H13M
Ranking: 83
Titulo: El infierno del odio
Rating: 8.4
Duracion: 2H23M
Ranking: 84
Titulo: Your Name.
Rating: 8.4
Duracion: 1H46M
Ranking: 85
Titulo: 3 Idiots
Rating: 8.4
Duracion: 2H50M
Ranking: 86
Titulo: Joker
Rating: 8.3
Duracion: 2H2M
Ranking: 87
Titulo: Érase una vez en América
Rating: 8.3
Duracion: 3H49M
Ranking: 88
Titulo: Cafarnaúm
Rating: 8.4
Duracion: 2H6M
Ranking: 89
Titulo: Cantando bajo la lluvia
Rating: 8.3
Duracion: 1H43M
Ranking: 90
Titulo: Masacre (Ven y mira)
Rating: 8.3
Duracion: 2H22M
Ranking: 91
Titulo: Réquiem por un sueño
Rating: 8.3
Duracion: 1H42M
Ranking: 92
Titulo: Hababam Sinifi: Sinifta Kaldi
Rating: 8.7
Duracion: 1H35M
Ranking: 93
Titulo: El retorno del jedi
Rating: 8.3
Duracion: 2H11M
Ranking: 94
Titulo: Toy Story 3
Rating: 8.3
Duracion: 1H43M
Ranking: 95
Titulo: La caza de Thomas Vinterberg
Rating: 8.3
Duracion: 1H55M
Ranking: 96
Titulo: Vivir
Rating: 8.3
Duracion: 2H23M
Ranking: 97
Titulo: ¡Olvídate de mí!
Rating: 8.3
Duracion: 1H48M
Ranking: 98
Titulo: 2001: Una odisea del espacio
Rating: 8.3
Duracion: 2H29M
Ranking: 99
Titulo: Incendios
Rating: 8.3
Duracion: 2H11M
Ranking: 100
Titulo: Reservoir Dogs
Rating: 8.3
Duracion: 1H39M
Ranking: 101
Titulo: El apartamento
Rating: 8.3
Duracion: 2H5M
Ranking: 102
Titulo: Lawrence de Arabia
Rating: 8.3
Duracion: 3H47M
Ranking: 103
Titulo: El precio del poder
Rating: 8.3
Duracion: 2H50M
Ranking: 104
Titulo: Perdición
Rating: 8.3
Duracion: 1H47M
Ranking: 105
Titulo: Heat
Rating: 8.3
Duracion: 2H50M
Ranking: 106
Titulo: Con la muerte en los talones
Rating: 8.3
Duracion: 2H16M
Ranking: 107
Titulo: Up
Rating: 8.3
Duracion: 1H36M
Ranking: 108
Titulo: Ciudadano Kane
Rating: 8.3
Duracion: 1H59M
Ranking: 109
Titulo: M, el vampiro de Düsseldorf
Rating: 8.3
Duracion: 1H57M
Ranking: 110
Titulo: La chaqueta metálica
Rating: 8.2
Duracion: 1H56M
Ranking: 111
Titulo: Vértigo (De entre los muertos)
Rating: 8.2
Duracion: 2H8M
Ranking: 112
Titulo: Amélie
Rating: 8.3
Duracion: 2H2M
Ranking: 113
Titulo: Nader y Simin, una separación
Rating: 8.3
Duracion: 2H3M
Ranking: 114
Titulo: Matar a un ruiseñor
Rating: 8.3
Duracion: 2H9M
Ranking: 115
Titulo: Taare Zameen Par
Rating: 8.3
Duracion: 2H42M
Ranking: 116
Titulo: La naranja mecánica
Rating: 8.2
Duracion: 2H16M
Ranking: 117
Titulo: Jungla de cristal
Rating: 8.2
Duracion: 2H12M
Ranking: 118
Titulo: El golpe
Rating: 8.2
Duracion: 2H9M
Ranking: 119
Titulo: Indiana Jones y la última cruzada
Rating: 8.2
Duracion: 2H7M
Ranking: 120
Titulo: Oppenheimer
Rating: 8.3
Duracion: 3H
Ranking: 121
Titulo: Metrópolis
Rating: 8.3
Duracion: 2H33M
Ranking: 122
Titulo: Snatch. Cerdos y diamantes
Rating: 8.2
Duracion: 1H44M
Ranking: 123
Titulo: 1917
Rating: 8.2
Duracion: 1H59M
Ranking: 124
Titulo: L.A. Confidential
Rating: 8.2
Duracion: 2H18M
Ranking: 125
Titulo: Ladrón de bicicletas
Rating: 8.2
Duracion: 1H29M
Ranking: 126
Titulo: El hundimiento
Rating: 8.2
Duracion: 2H36M
Ranking: 127
Titulo: Dangal
Rating: 8.3
Duracion: 2H41M
Ranking: 128
Titulo: El lobo de Wall Street
Rating: 8.2
Duracion: 3H
Ranking: 129
Titulo: Hamilton
Rating: 8.3
Duracion: 2H40M
Ranking: 130
Titulo: Taxi Driver
Rating: 8.2
Duracion: 1H54M
Ranking: 131
Titulo: Green Book
Rating: 8.2
Duracion: 2H10M
Ranking: 132
Titulo: Batman Begins
Rating: 8.2
Duracion: 2H20M
Ranking: 133
Titulo: La muerte tenía un precio
Rating: 8.2
Duracion: 2H12M
Ranking: 134
Titulo: El show de Truman
Rating: 8.2
Duracion: 1H43M
Ranking: 135
Titulo: Vencedores o vencidos
Rating: 8.3
Duracion: 2H59M
Ranking: 136
Titulo: Con faldas y a lo loco
Rating: 8.2
Duracion: 2H1M
Ranking: 137
Titulo: Shutter Island
Rating: 8.2
Duracion: 2H18M
Ranking: 138
Titulo: El chico
Rating: 8.2
Duracion: 1H8M
Ranking: 139
Titulo: El padre
Rating: 8.2
Duracion: 1H37M
Ranking: 140
Titulo: Eva al desnudo
Rating: 8.2
Duracion: 2H18M
Ranking: 141
Titulo: Jurassic Park (Parque Jurásico)
Rating: 8.2
Duracion: 2H7M
Ranking: 142
Titulo: Pozos de ambición
Rating: 8.2
Duracion: 2H38M
Ranking: 143
Titulo: El sexto sentido
Rating: 8.2
Duracion: 1H47M
Ranking: 144
Titulo: Casino
Rating: 8.2
Duracion: 2H58M
Ranking: 145
Titulo: Ran
Rating: 8.2
Duracion: 2H40M
Ranking: 146
Titulo: Top Gun: Maverick
Rating: 8.2
Duracion: 2H10M
Ranking: 147
Titulo: No es país para viejos
Rating: 8.2
Duracion: 2H2M
Ranking: 148
Titulo: La cosa (El enigma de otro mundo)
Rating: 8.2
Duracion: 1H49M
Ranking: 149
Titulo: El laberinto del fauno
Rating: 8.2
Duracion: 1H58M
Ranking: 150
Titulo: Sin perdón
Rating: 8.2
Duracion: 2H10M
Ranking: 151
Titulo: Una mente maravillosa
Rating: 8.2
Duracion: 2H15M
Ranking: 152
Titulo: Kill Bill: Volumen 1
Rating: 8.2
Duracion: 1H51M
Ranking: 153
Titulo: El tesoro de Sierra Madre
Rating: 8.2
Duracion: 2H6M
Ranking: 154
Titulo: Prisioneros
Rating: 8.2
Duracion: 2H33M
Ranking: 155
Titulo: Yojimbo
Rating: 8.2
Duracion: 1H50M
Ranking: 156
Titulo: Buscando a Nemo
Rating: 8.2
Duracion: 1H40M
Ranking: 157
Titulo: El castillo ambulante
Rating: 8.2
Duracion: 1H59M
Ranking: 158
Titulo: La gran evasión
Rating: 8.2
Duracion: 2H52M
Ranking: 159
Titulo: Los caballeros de la mesa cuadrada y sus locos seguidores
Rating: 8.2
Duracion: 1H31M
Ranking: 160
Titulo: El hombre elefante
Rating: 8.2
Duracion: 2H4M
Ranking: 161
Titulo: Crimen perfecto
Rating: 8.2
Duracion: 1H45M
Ranking: 162
Titulo: Klaus
Rating: 8.2
Duracion: 1H36M
Ranking: 163
Titulo: Lo que el viento se llevó
Rating: 8.2
Duracion: 3H58M
Ranking: 164
Titulo: Rashomon
Rating: 8.2
Duracion: 1H28M
Ranking: 165
Titulo: Chinatown
Rating: 8.1
Duracion: 2H10M
Ranking: 166
Titulo: El secreto de sus ojos
Rating: 8.2
Duracion: 2H9M
Ranking: 167
Titulo: Lock &amp; Stock
Rating: 8.1
Duracion: 1H47M
Ranking: 168
Titulo: V de vendetta
Rating: 8.1
Duracion: 2H12M
Ranking: 169
Titulo: Del revés (Inside Out)
Rating: 8.1
Duracion: 1H35M
Ranking: 170
Titulo: Tres anuncios en las afueras
Rating: 8.1
Duracion: 1H55M
Ranking: 171
Titulo: El puente sobre el río Kwai
Rating: 8.1
Duracion: 2H41M
Ranking: 172
Titulo: Trainspotting
Rating: 8.1
Duracion: 1H33M
Ranking: 173
Titulo: Atrápame si puedes
Rating: 8.1
Duracion: 2H21M
Ranking: 174
Titulo: Toro salvaje
Rating: 8.1
Duracion: 2H9M
Ranking: 175
Titulo: Robot salvaje
Rating: 8.2
Duracion: 1H42M
Ranking: 176
Titulo: Fargo
Rating: 8.1
Duracion: 1H38M
Ranking: 177
Titulo: Warrior
Rating: 8.1
Duracion: 2H20M
Ranking: 178
Titulo: Harry Potter y las Reliquias de la Muerte: Parte 2
Rating: 8.1
Duracion: 2H10M
Ranking: 179
Titulo: Gran Torino
Rating: 8.1
Duracion: 1H56M
Ranking: 180
Titulo: Million Dollar Baby
Rating: 8.1
Duracion: 2H12M
Ranking: 181
Titulo: Ben-Hur
Rating: 8.1
Duracion: 3H32M
Ranking: 182
Titulo: Mad Max: Furia en la carretera
Rating: 8.1
Duracion: 2H
Ranking: 183
Titulo: Mi vecino Totoro
Rating: 8.1
Duracion: 1H26M
Ranking: 184
Titulo: Barry Lyndon
Rating: 8.1
Duracion: 3H5M
Ranking: 185
Titulo: Spider-Man: No Way Home
Rating: 8.2
Duracion: 2H28M
Ranking: 186
Titulo: El club de los poetas muertos
Rating: 8.1
Duracion: 2H8M
Ranking: 187
Titulo: Children of Heaven
Rating: 8.2
Duracion: 1H29M
Ranking: 188
Titulo: 12 años de esclavitud
Rating: 8.1
Duracion: 2H14M
Ranking: 189
Titulo: Antes de amanecer
Rating: 8.1
Duracion: 1H41M
Ranking: 190
Titulo: El gran hotel Budapest
Rating: 8.1
Duracion: 1H39M
Ranking: 191
Titulo: Hasta el último hombre (Hacksaw Ridge)
Rating: 8.1
Duracion: 2H19M
Ranking: 192
Titulo: Blade Runner
Rating: 8.1
Duracion: 1H57M
Ranking: 193
Titulo: Perdida
Rating: 8.1
Duracion: 2H29M
Ranking: 194
Titulo: Memories of Murder (Crónica de un asesino en serie)
Rating: 8.1
Duracion: 2H11M
Ranking: 195
Titulo: Ratatouille
Rating: 8.1
Duracion: 1H51M
Ranking: 196
Titulo: Monstruos, S.A.
Rating: 8.1
Duracion: 1H32M
Ranking: 197
Titulo: En el nombre del padre
Rating: 8.1
Duracion: 2H13M
Ranking: 198
Titulo: How to Train Your Dragon
Rating: 8.1
Duracion: 1H38M
Ranking: 199
Titulo: Relatos salvajes
Rating: 8.1
Duracion: 2H2M
Ranking: 200
Titulo: La quimera del oro
Rating: 8.1
Duracion: 1H35M
Ranking: 201
Titulo: El moderno Sherlock Holmes
Rating: 8.2
Duracion: 45M
Ranking: 202
Titulo: Tiburón
Rating: 8.1
Duracion: 2H4M
Ranking: 203
Titulo: Mary and Max
Rating: 8.1
Duracion: 1H32M
Ranking: 204
Titulo: El cazador
Rating: 8.1
Duracion: 3H3M
Ranking: 205
Titulo: Le Mans &apos;66
Rating: 8.1
Duracion: 2H32M
Ranking: 206
Titulo: El maquinista de La General
Rating: 8.1
Duracion: 1H18M
Ranking: 207
Titulo: El salario del miedo
Rating: 8.1
Duracion: 2H36M
Ranking: 208
Titulo: Caballero sin espada
Rating: 8.1
Duracion: 2H9M
Ranking: 209
Titulo: La ley del silencio
Rating: 8.1
Duracion: 1H48M
Ranking: 210
Titulo: Fresas salvajes
Rating: 8.1
Duracion: 1H32M
Ranking: 211
Titulo: Logan
Rating: 8.1
Duracion: 2H17M
Ranking: 212
Titulo: Rocky
Rating: 8.1
Duracion: 2H
Ranking: 213
Titulo: El tercer hombre
Rating: 8.1
Duracion: 1H44M
Ranking: 214
Titulo: Cuentos de Tokio
Rating: 8.1
Duracion: 2H17M
Ranking: 215
Titulo: Spotlight
Rating: 8.1
Duracion: 2H9M
Ranking: 216
Titulo: El gran Lebowski
Rating: 8.1
Duracion: 1H57M
Ranking: 217
Titulo: Maharaja
Rating: 8.4
Duracion: 2H21M
Ranking: 218
Titulo: Terminator
Rating: 8.1
Duracion: 1H47M
Ranking: 219
Titulo: El séptimo sello
Rating: 8.1
Duracion: 1H36M
Ranking: 220
Titulo: Piratas del Caribe: La maldición de la Perla Negra
Rating: 8.1
Duracion: 2H23M
Ranking: 221
Titulo: La habitación
Rating: 8.1
Duracion: 1H58M
Ranking: 222
Titulo: Aún estoy aquí
Rating: 8.3
Duracion: 2H17M
Ranking: 223
Titulo: El odio
Rating: 8.1
Duracion: 1H38M
Ranking: 224
Titulo: Jai Bhim
Rating: 8.6
Duracion: 2H44M
Ranking: 225
Titulo: Hotel Rwanda
Rating: 8.1
Duracion: 2H1M
Ranking: 226
Titulo: Platoon
Rating: 8.1
Duracion: 2H
Ranking: 227
Titulo: Los mejores años de nuestra vida
Rating: 8.1
Duracion: 2H50M
Ranking: 228
Titulo: Antes del atardecer
Rating: 8.1
Duracion: 1H20M
Ranking: 229
Titulo: El exorcista
Rating: 8.1
Duracion: 2H2M
Ranking: 230
Titulo: Sonrisas y lágrimas
Rating: 8.1
Duracion: 2H52M
Ranking: 231
Titulo: La pasión de Juana de Arco
Rating: 8.1
Duracion: 1H50M
Ranking: 232
Titulo: El mago de Oz
Rating: 8.1
Duracion: 1H42M
Ranking: 233
Titulo: Los Increíbles
Rating: 8
Duracion: 1H55M
Ranking: 234
Titulo: Siempre a tu lado (Hachiko)
Rating: 8.1
Duracion: 1H33M
Ranking: 235
Titulo: Rush
Rating: 8.1
Duracion: 2H3M
Ranking: 236
Titulo: Cuenta conmigo
Rating: 8.1
Duracion: 1H29M
Ranking: 237
Titulo: Mi padre y mi hijo
Rating: 8.2
Duracion: 1H52M
Ranking: 238
Titulo: Network, un mundo implacable
Rating: 8.1
Duracion: 2H1M
Ranking: 239
Titulo: El gigante de hierro
Rating: 8.1
Duracion: 1H26M
Ranking: 240
Titulo: La doncella
Rating: 8.1
Duracion: 2H25M
Ranking: 241
Titulo: A Silent Voice
Rating: 8.1
Duracion: 2H10M
Ranking: 242
Titulo: Ser o no ser
Rating: 8.1
Duracion: 1H39M
Ranking: 243
Titulo: La batalla de Argel
Rating: 8.1
Duracion: 2H1M
Ranking: 244
Titulo: Las uvas de la ira
Rating: 8.1
Duracion: 2H9M
Ranking: 245
Titulo: Hacia rutas salvajes
Rating: 8
Duracion: 2H28M
Ranking: 246
Titulo: Atrapado en el tiempo
Rating: 8
Duracion: 1H41M
Ranking: 247
Titulo: Criadas y señoras (The Help)
Rating: 8.1
Duracion: 2H26M
Ranking: 248
Titulo: Amores perros
Rating: 8
Duracion: 2H34M
Ranking: 249
Titulo: Drishyam
Rating: 8.2
Duracion: 2H43M
Ranking: 250
Titulo: Rebeca
Rating: 8.1
Duracion: 2H10M

In [84]:
for x in data_2["props"]["pageProps"]["pageData"]["chartTitles"]["edges"]:
    print(x["node"]["releaseYear"]["year"])
    print("_______________________________________________________")

1994
_______________________________________________________
1972
_______________________________________________________
2008
_______________________________________________________
1974
_______________________________________________________
1957
_______________________________________________________
2003
_______________________________________________________
1993
_______________________________________________________
1994
_______________________________________________________
2001
_______________________________________________________
1966
_______________________________________________________
1994
_______________________________________________________
2002
_______________________________________________________
1999
_______________________________________________________
2010
_______________________________________________________
1980
_______________________________________________________
1999
_______________________________________________________
1990
_______________________________________________________
2014
_______________________________________________________
1975
_______________________________________________________
1995
_______________________________________________________
1946
_______________________________________________________
1991
_______________________________________________________
1954
_______________________________________________________
1998
_______________________________________________________
2002
_______________________________________________________
1999
_______________________________________________________
1997
_______________________________________________________
1991
_______________________________________________________
1977
_______________________________________________________
1985
_______________________________________________________
2001
_______________________________________________________
2002
_______________________________________________________
2000
_______________________________________________________
2019
_______________________________________________________
1960
_______________________________________________________
1994
_______________________________________________________
1988
_______________________________________________________
2006
_______________________________________________________
2014
_______________________________________________________
1962
_______________________________________________________
2006
_______________________________________________________
1998
_______________________________________________________
1994
_______________________________________________________
2023
_______________________________________________________
1942
_______________________________________________________
1995
_______________________________________________________
2011
_______________________________________________________
1988
_______________________________________________________
1979
_______________________________________________________
1936
_______________________________________________________
1954
_______________________________________________________
1968
_______________________________________________________
2012
_______________________________________________________
1931
_______________________________________________________
1979
_______________________________________________________
2024
_______________________________________________________
2008
_______________________________________________________
2000
_______________________________________________________
1981
_______________________________________________________
2006
_______________________________________________________
2018
_______________________________________________________
1950
_______________________________________________________
2018
_______________________________________________________
1957
_______________________________________________________
1957
_______________________________________________________
1980
_______________________________________________________
1940
_______________________________________________________
2023
_______________________________________________________
2009
_______________________________________________________
1986
_______________________________________________________
2012
_______________________________________________________
2017
_______________________________________________________
1984
_______________________________________________________
1995
_______________________________________________________
2019
_______________________________________________________
1997
_______________________________________________________
2003
_______________________________________________________
1964
_______________________________________________________
1981
_______________________________________________________
1995
_______________________________________________________
1999
_______________________________________________________
1997
_______________________________________________________
1963
_______________________________________________________
2016
_______________________________________________________
2009
_______________________________________________________
2019
_______________________________________________________
1984
_______________________________________________________
2018
_______________________________________________________
1952
_______________________________________________________
1985
_______________________________________________________
2000
_______________________________________________________
1975
_______________________________________________________
1983
_______________________________________________________
2010
_______________________________________________________
2012
_______________________________________________________
1952
_______________________________________________________
2004
_______________________________________________________
1968
_______________________________________________________
2010
_______________________________________________________
1992
_______________________________________________________
1960
_______________________________________________________
1962
_______________________________________________________
1983
_______________________________________________________
1944
_______________________________________________________
1995
_______________________________________________________
1959
_______________________________________________________
2009
_______________________________________________________
1941
_______________________________________________________
1931
_______________________________________________________
1987
_______________________________________________________
1958
_______________________________________________________
2001
_______________________________________________________
2011
_______________________________________________________
1962
_______________________________________________________
2007
_______________________________________________________
1971
_______________________________________________________
1988
_______________________________________________________
1973
_______________________________________________________
1989
_______________________________________________________
2023
_______________________________________________________
1927
_______________________________________________________
2000
_______________________________________________________
2019
_______________________________________________________
1997
_______________________________________________________
1948
_______________________________________________________
2004
_______________________________________________________
2016
_______________________________________________________
2013
_______________________________________________________
2020
_______________________________________________________
1976
_______________________________________________________
2018
_______________________________________________________
2005
_______________________________________________________
1965
_______________________________________________________
1998
_______________________________________________________
1961
_______________________________________________________
1959
_______________________________________________________
2010
_______________________________________________________
1921
_______________________________________________________
2020
_______________________________________________________
1950
_______________________________________________________
1993
_______________________________________________________
2007
_______________________________________________________
1999
_______________________________________________________
1995
_______________________________________________________
1985
_______________________________________________________
2022
_______________________________________________________
2007
_______________________________________________________
1982
_______________________________________________________
2006
_______________________________________________________
1992
_______________________________________________________
2001
_______________________________________________________
2003
_______________________________________________________
1948
_______________________________________________________
2013
_______________________________________________________
1961
_______________________________________________________
2003
_______________________________________________________
2004
_______________________________________________________
1963
_______________________________________________________
1975
_______________________________________________________
1980
_______________________________________________________
1954
_______________________________________________________
2019
_______________________________________________________
1939
_______________________________________________________
1950
_______________________________________________________
1974
_______________________________________________________
2009
_______________________________________________________
1998
_______________________________________________________
2005
_______________________________________________________
2015
_______________________________________________________
2017
_______________________________________________________
1957
_______________________________________________________
1996
_______________________________________________________
2002
_______________________________________________________
1980
_______________________________________________________
2024
_______________________________________________________
1996
_______________________________________________________
2011
_______________________________________________________
2011
_______________________________________________________
2008
_______________________________________________________
2004
_______________________________________________________
1959
_______________________________________________________
2015
_______________________________________________________
1988
_______________________________________________________
1975
_______________________________________________________
2021
_______________________________________________________
1989
_______________________________________________________
1997
_______________________________________________________
2013
_______________________________________________________
1995
_______________________________________________________
2014
_______________________________________________________
2016
_______________________________________________________
1982
_______________________________________________________
2014
_______________________________________________________
2003
_______________________________________________________
2007
_______________________________________________________
2001
_______________________________________________________
1993
_______________________________________________________
2010
_______________________________________________________
2014
_______________________________________________________
1925
_______________________________________________________
1924
_______________________________________________________
1975
_______________________________________________________
2009
_______________________________________________________
1978
_______________________________________________________
2019
_______________________________________________________
1926
_______________________________________________________
1953
_______________________________________________________
1939
_______________________________________________________
1954
_______________________________________________________
1957
_______________________________________________________
2017
_______________________________________________________
1976
_______________________________________________________
1949
_______________________________________________________
1953
_______________________________________________________
2015
_______________________________________________________
1998
_______________________________________________________
2024
_______________________________________________________
1984
_______________________________________________________
1957
_______________________________________________________
2003
_______________________________________________________
2015
_______________________________________________________
2024
_______________________________________________________
1995
_______________________________________________________
2021
_______________________________________________________
2004
_______________________________________________________
1986
_______________________________________________________
1946
_______________________________________________________
2004
_______________________________________________________
1973
_______________________________________________________
1965
_______________________________________________________
1928
_______________________________________________________
1939
_______________________________________________________
2004
_______________________________________________________
2009
_______________________________________________________
2013
_______________________________________________________
1986
_______________________________________________________
2005
_______________________________________________________
1976
_______________________________________________________
1999
_______________________________________________________
2016
_______________________________________________________
2016
_______________________________________________________
1942
_______________________________________________________
1966
_______________________________________________________
1940
_______________________________________________________
2007
_______________________________________________________
1993
_______________________________________________________
2011
_______________________________________________________
2000
_______________________________________________________
2015
_______________________________________________________
1940
_______________________________________________________

In [85]:
dict_pelicula = {
    "Ranking": [x["currentRank"] for x in data_2["props"]["pageProps"]["pageData"]["chartTitles"]["edges"]],
    "Titulo": [x["item"].get("alternateName", x["item"]["name"]) for x in data["itemListElement"]],
    "Año": [x["node"]["releaseYear"]["year"] for x in data_2["props"]["pageProps"]["pageData"]["chartTitles"]["edges"]],
    "Duraccion": [x["item"]["duration"][2:] for x in data["itemListElement"]],
    "Rating": [x["item"]["aggregateRating"]["ratingValue"] for x in data["itemListElement"]] 
                  
}

df = pd.DataFrame(dict_pelicula)

In [86]:
df

     Ranking                        Titulo   Año Duraccion  Rating
0          1               Cadena perpetua  1994     2H22M     9.3
1          2                    El padrino  1972     2H55M     9.2
2          3           El caballero oscuro  2008     2H32M     9.0
3          4           El padrino parte II  1974     3H22M     9.0
4          5         12 hombres sin piedad  1957     1H36M     9.0
..       ...                           ...   ...       ...     ...
245      246         Atrapado en el tiempo  1993     1H41M     8.0
246      247  Criadas y señoras (The Help)  2011     2H26M     8.1
247      248                 Amores perros  2000     2H34M     8.0
248      249                      Drishyam  2015     2H43M     8.2
249      250                        Rebeca  1940     2H10M     8.1

[250 rows x 5 columns]